### ISSUE TITLE
Channels not autoconnecting

### ISSUE THREAD

**Issue by rodneyrod** [agronick/Relay#13]
Created a new server connection, added a few channels and set them to autoconnect, but after connecting to the server, it stops there. There are no new tabs open for the auto connected rooms, they have to be opened manually.

**Comment by agronick** [comment]
It never gets the welcome signal then. Can you run it with the -d flag and see if its getting any messages that it doesn't know what to do with. Or is there errors being displayed in the server connection window. If you have visible errors in the server connection window then it is expected behavior.

**Comment by rodneyrod** [comment]
All good, it auto opens after restarting the client.

**Comment by agronick** [comment]
Yeah autoconnect is what it does on startup.
