### ISSUE TITLE
Add support for utf-8 "wide chars"

### ISSUE THREAD

**Issue by inizan-yannick** [agronick/Relay#6]
some languages use 'é', 'à', .. characters. in utf-8 these characters are encoded with 2 bytes. the message is displayed correctly on screen but on distant client we have an ugly message : \x303\x251\x303\x240 for "àé" text

**Comment by agronick** [comment]
Good to see that someone is actually using it. I'll see what I can do.

**Comment by inizan-yannick** [comment]
I knew your project by Elementary french community :)

**Comment by inizan-yannick** [comment]
you don't understand. read line works, it's write data the problem. your modification raises another error
```
file connection.c: line 517: unexpected error: Séquence d'octets incorrecte en entrée du convertisseur (g_convert_error, 1)
```

**Comment by agronick** [comment]
Does the edian have anything to do with that? They don't have a write utf8 function. They do have this: http://valadoc.org/#!api=gio-2.0/GLib.DataStreamByteOrder

It says in the doc: Determines the byte ordering that is used when writing multi-byte entities (such as integers) to the stream.

Since these characters are multi byte entities I figure it might have something to do with that.
So all the reading worked fine when that function was just read_line?

**Comment by inizan-yannick** [comment]
with read_line function, Relay works.

**Comment by agronick** [comment]
Ok I restored it

**Comment by agronick** [comment]
You don't have any idea how you would use printf do unescape the string? I'm googling and trying to find a way to fix this on a testing IRC server.
